# Generated by Django 4.1.2 on 2022-11-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankexp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequingtransaction',
            name='tr_balance',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Transaction Balance', max_digits=10, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='creditcardtransaction',
            name='tr_balance',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Transaction Balance', max_digits=10, null=True, verbose_name='Balance'),
        ),
    ]
